project:
  type: website
  render:
    - "*.md"
    - "*.qmd"

website:

  repo-url: https://github.com/watdev-eu/ui-model
  repo-actions:
    - edit
    - issue
  page-footer:
    left:
    - text: WATDEV EU 2025
      file: https://www.watdev.eu
  title: "WATDEV"
  search: true
  navbar:
    pinned: true
    logo: https://static.wixstatic.com/media/9d090e_49fe8f50a4324adab5d65434391395d5~mv2.png/v1/fill/w_444,h_108,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/DEF2.png
    right:
      - text: Home
        file: "/"
format: html
